services:
  web:
    build:
      context: ./docker/php
    container_name: cardfactory-apache
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
      - "5173:5173"
    depends_on:
      - db
    networks:
      - cardfactory_network

  db:
    image: mysql:8.0
    container_name: cardfactory-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_segura
      MYSQL_DATABASE: cardfactory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password_segura
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cardfactory_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cardfactory-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 
    depends_on:
      - db
    networks:
      - cardfactory_network
      
# ----------------------------------------------------
# 4. REDES Y VOLÃšMENES
# ----------------------------------------------------
networks:
  cardfactory_network:
    driver: bridge

volumes:
  dbdata: